import csv
from apify_client import ApifyClient

# Initialize the ApifyClient with your API token
client = ApifyClient("apify_api_Mcre4QCUttaxzxFcSAM7kqESgEwUWt4mJ3bq")


task_id = "rohan12345/instagram-scraper-task"
run = client.task(task_id).call()

# Fetch the dataset ID generated by the run
dataset_id = run["defaultDatasetId"]

# Fetch data from the dataset using Apify's dataset API
instagram_data = client.dataset(dataset_id).iterate_items()

# Save data to CSV
with open('instagram_results.csv', mode='w', newline='', encoding='utf-8') as file:
    fieldnames = ['type', 'caption', 'url', 'likes', 'comments']
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()

    # Iterate over the fetched items and save them to CSV
    for item in instagram_data:
        writer.writerow({
            'type': item.get('type', ''),
            'caption': item.get('caption', ''),
            'url': item.get('url', ''),
            'likes': item.get('likes', 0),
            'comments': item.get('comments', 0)
        })

print("Instagram data saved to 'instagram_results.csv'")
